export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CURRENT_USER = 'AUTH_CURRENT_USER';

export const CREATE_TASK_START = 'CREATE_TASK_START';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAIL = 'CREATE_TASK_FAIL';

export const DELETE_TASK_START = 'DELETE_TASK_START';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAIL = 'DELETE_TASK_FAIL';

export const FETCH_TASK_START = 'FETCH_TASK_START';
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';
export const FETCH_TASK_FAIL = 'FETCH_TASK_FAIL';

export const FETCH_TASK_DETAIL_START = 'FETCH_TASK_DETAIL_START';
export const FETCH_TASK_DETAIL_SUCCESS = 'FETCH_TASK_DETAIL_SUCCESS';
export const FETCH_TASK_DETAIL_FAIL = 'FETCH_TASK_DETAIL_FAIL';

export const FETCH_WEEK_TASKS_START = 'FETCH_WEEK_TASKS_START';
export const FETCH_WEEK_TASKS_SUCCESS = 'FETCH_WEEK_TASKS_SUCCESS';
export const FETCH_WEEK_TASKS_FAIL = 'FETCH_WEEK_TASKS_FAIL';

export const CREATE_TEAM_START = 'CREATE_TEAM_START';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const CREATE_TEAM_FAIL = 'CREATE_TEAM_FAIL';

export const REMOVE_TEAM_START = 'REMOVE_TEAM_START';
export const REMOVE_TEAM_SUCCESS = 'REMOVE_TEAM_SUCCESS';
export const REMOVE_TEAM_FAIL = 'REMOVE_TEAM_FAIL';

export const UPDATE_TEAM_START = 'UPDATE_TEAM_START';
export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS';
export const UPDATE_TEAM_FAIL = 'UPDATE_TEAM_FAIL';

export const FETCH_TEAM_START = 'FETCH_TEAM_START';
export const FETCH_TEAM_SUCCESS = 'FETCH_TEAM_SUCCESS';
export const FETCH_TEAM_FAIL = 'FETCH_TEAM_FAIL';

export const FETCH_TEAM_DETAILS_START = 'FETCH_TEAM_DETAILS_START';
export const FETCH_TEAM_DETAILS_SUCCESS = 'FETCH_TEAM_DETAILS_SUCCESS';
export const FETCH_TEAM_DETAILS_FAIL = 'FETCH_TEAM_DETAILS_FAIL';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const REMOVE_USERS = 'REMOVE_USERS';

export const CREATE_WEEK_HOURS_START = 'CREATE_WEEK_HOURS_START';
export const CREATE_WEEK_HOURS_SUCCESS = 'CREATE_WEEK_HOURS_SUCCESS';
export const CREATE_WEEK_HOURS_FAIL = 'CREATE_WEEK_HOURS_FAIL';

export const FETCH_WEEK_HOURS_START = 'FETCH_WEEK_HOURS_START';
export const FETCH_WEEK_HOURS_SUCCESS = 'FETCH_WEEK_HOURS_SUCCESS';
export const FETCH_WEEK_HOURS_FAIL = 'FETCH_WEEK_HOURS_FAIL';

export const FETCH_WEEK_TEAM_HOURS_START = 'FETCH_WEEK_TEAM_HOURS_START';
export const FETCH_WEEK_TEAM_HOURS_SUCCESS = 'FETCH_WEEK_TEAM_HOURS_SUCCESS';
export const FETCH_WEEK_TEAM_HOURS_FAIL = 'FETCH_WEEK_TEAM_HOURS_FAIL';